neptune: True
seed: 42
device: 'cuda'

model_path: '/users/scratch1/jbuler/models-xai-eval'
model: "r18"
shared_att: False

is_MCDO-val: False
is_MCDO-test: True
N: 50
feature_dropout: 0.1
attention_dropout: 0.1

data:
  fraction_train_rest: 0.75
  fraction_val_test: 0.5
  root_path: '/users/project1/pt01190/TOMPEI-CMMD'
  metadata_path: '/users/project1/pt01190/TOMPEI-CMMD/df_with_masks.pkl'
  
  patch_size: 128
  overlap: 0.5
  empty_threshold: 0.75
  bag_size: -1

  # cv_folds: 5
  # fraction_test: 0.15

training_plan:
  parameters:
    batch_size: 1
    num_workers: 8
    lr: 0.001
    wd: 0.001
    epochs: 1000
    patience: 50
    grad_acc_steps: 2

  criterion: 'ce'
  optimizer: 'sgd'

  scheduler:
    name: 'lin'
    step_size: 100
    gamma: 0.9